spring.application.name=Smart-Research-Assistant

server.port=${PORT:10000}

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent
gemini.api.key=${GEMINI_API_KEY}